# Generated by Django 6.0.6 on 2026-06-29 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notes',
            new_name='Note',
        ),
    ]
